vim.o.number = true -- number of lines
vim.o.relativenumber = true
vim.o.encoding="utf-8"
vim.o.autoindent = true -- автооступ
vim.o.tabstop=4 -- ширина таба
vim.o.shiftwidth=4
vim.o.smarttab = true 
vim.o.softtabstop=4
vim.o.mouse="a" -- активация мыши
vim.o.clipboard="unnamedplus" -- use system clipboard
vim.o.completeopt = "preview"
vim.o.t_Co=256
vim.o.t_ut=false
